# Generated by Django 5.2.4 on 2025-07-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='note',
            field=models.JSONField(default=dict),
        ),
    ]
