# Generated by Django 5.2.4 on 2025-07-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_session_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
